/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue", 
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue"
  ],
  safelist: [
    'bg-white',
    'bg-gray-50',
    'bg-gray-100',
    'bg-green-500',
    'border',
    'border-gray-200',
    'border-t',
    'border-b',
    'text-gray-900',
    'text-gray-800',
    'text-gray-700',
    'text-gray-600',
    'text-gray-500',
    'text-2xl',
    'text-xl',
    'text-lg',
    'text-sm',
    'text-xs',
    'shadow-sm',
    'shadow-lg',
    'shadow-xl',
    'rounded-lg',
    'rounded-xl',
    'rounded-full',
    'px-3',
    'px-4',
    'px-6',
    'px-8',
    'py-2',
    'py-3',
    'py-6',
    'py-8',
    'py-12',
    'mt-1',
    'mt-4',
    'mb-2',
    'mb-4',
    'max-w-6xl',
    'min-h-screen',
    'font-bold',
    'font-medium',
    'font-semibold',
    'space-x-4',
    'space-y-3',
    'space-y-8',
    'grid',
    'gap-4',
    'gap-8',
    'w-2',
    'w-16',
    'h-2',
    'h-16',
    'lg:grid-cols-12',
    'lg:col-span-7',
    'lg:col-span-5',
    'sm:grid-cols-2',
    'animate-pulse',
    'sticky',
    'top-32'
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
